language: csharp
solution: src/kOS.sln
sudo: false

# Pre-shared token for pushing notifications to slack chat
notifications:
  slack: ksp-kos:51DTQ4ZBP9SlGNnLWJ5D84vp

# Before the install the library dlls need to be downloaded
before_install:
- wget --quiet https://github.com/KSP-KOS/KSP_LIB/blob/master/kos-1.0.5.tar.enc?raw=true
- openssl aes-256-cbc -K $encrypted_6287ee711a27_key -iv $encrypted_6287ee711a27_iv -in kos-1.0.5.tar.enc -out kos-1.0.5.tar -d
- mkdir -p Resources
- tar -xvf kos-1.0.5.tar -C Resources/

# Cleanup the downloaded resources
after_script:
- cd Resources
- rm *.dll
- cd ../

before_deploy:
- mkdir src/kOS/bin/dist 
- tar -zcvf src/kOS/bin/dist/build_$TRAVIS_BUILD_NUMBER.tgz src/kOS/bin/Release/kOS*.dll

deploy:
  provider: s3
  access_key_id: "AKIAINHSGTBU5O3DKV2Q"
  secret_access_key: "$S3_DEPLOY_SECRET"
  bucket: "kos-artifacts"
  skip_cleanup: true
  local_dir: "src/kOS/bin/dist/"
