language: csharp
solution: src/kOS.sln
sudo: false

addons:
  apt:
    packages:
    - python-sphinx
    - nunit-console

env:
- KSP_VERSION = 1.0.5

# Pre-shared token for pushing notifications to slack chat
notifications:
  slack: ksp-kos:51DTQ4ZBP9SlGNnLWJ5D84vp

# Before the install the library dlls need to be downloaded
before_script:
- chmod +x .ci/travis/before_script.sh && ./.ci/travis/before_script.sh

script:
- xbuild /p:Configuration=Release $TRAVIS_SOLUTION
# I know framework 4.0 is wrong, just trying it to see if it fixes the test
- nunit-console -framework=4.0 src/kOS.Safe.Test/bin/Release/kOS.Safe.Test.dll
# - chmod +x .ci/travis/script-sphinxdocs.sh && ./.ci/travis/script-sphinxdocs.sh

# Cleanup the downloaded resources
after_script:
- chmod +x .ci/travis/after_script.sh && ./.ci/travis/after_script.sh

before_deploy:
- mkdir src/kOS/bin/dist 
- tar -zcvf src/kOS/bin/dist/build_$TRAVIS_BUILD_NUMBER.tgz src/kOS/bin/Release/kOS*.dll

deploy:
  provider: s3
  access_key_id: "AKIAINHSGTBU5O3DKV2Q"
  secret_access_key: "$S3_DEPLOY_SECRET"
  bucket: "kos-artifacts"
  skip_cleanup: true
  local_dir: "src/kOS/bin/dist/"
